version: '3.9'

services:
  reverse-proxy:
    image: traefik:v2.9
    command: >
      --providers.docker
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  default:
    name: traefik
    driver: bridge


